// <auto-generated />
using System;
using Jabez.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jabez.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223064106_AddSuperAdmin")]
    partial class AddSuperAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationType")
                        .IsUnique()
                        .HasFilter("[ApplicationType] IS NOT NULL");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApprovalItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationType = "leave",
                            Code = "leave_request",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "請假申請"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationType = "payment_request",
                            Code = "purchase_request",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "採購申請"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReviewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("ApplicationType", "ApplicationId", "StepOrder");

                    b.ToTable("ApprovalRecords", (string)null);
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalItemId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("ApprovalSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalItemId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            JobTitleId = 4,
                            Note = "直屬部門主管核可",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovalItemId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Note = "管理部最終確認",
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ApprovalItemId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitleId = 4,
                            Note = "部門主管初核",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            ApprovalItemId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            JobTitleId = 4,
                            Note = "管理部主管最終核可",
                            StepOrder = 2
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MGT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "管理部",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "IT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "資訊部",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "SLS",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "業務部",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PaymentRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15000m,
                            FileName = "invoice_001.jpg",
                            InvoiceNo = "AB-12345678",
                            PaymentRequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8500m,
                            FileName = "invoice_002.jpg",
                            InvoiceNo = "CD-87654321",
                            PaymentRequestId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 4200m,
                            FileName = "receipt_hotel.jpg",
                            InvoiceNo = "EF-11223344",
                            PaymentRequestId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 980m,
                            FileName = "receipt_train.jpg",
                            InvoiceNo = "GH-55667788",
                            PaymentRequestId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 20000m,
                            FileName = "advance_001.jpg",
                            InvoiceNo = "IJ-99887766",
                            PaymentRequestId = 3
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            Name = "工程師"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 2,
                            Name = "資深工程師"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 3,
                            Name = "主任工程師"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 4,
                            Name = "部門主管"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalItemId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStepOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Days")
                        .HasColumnType("decimal(5,1)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalItemId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalItemId = 1,
                            ApprovalStatus = "pending",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            Days = 5m,
                            EmployeeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveType = "annual",
                            Reason = "個人旅遊",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApprovalItemId = 1,
                            ApprovalStatus = "approved",
                            CreatedAt = new DateTime(2026, 2, 20, 7, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            Days = 2m,
                            EmployeeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            EndDate = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveType = "sick",
                            Reason = "身體不適就醫",
                            ReviewNote = "核准",
                            ReviewedAt = new DateTime(2026, 2, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ApprovalItemId = 1,
                            ApprovalStatus = "rejected",
                            CreatedAt = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            Days = 1m,
                            EmployeeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeaveType = "compensatory",
                            Reason = "補休加班時數",
                            ReviewNote = "補休時數不足，請確認後重新申請",
                            ReviewedAt = new DateTime(2026, 2, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.PaymentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalItemId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStepOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalItemId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SubmittedById");

                    b.ToTable("PaymentRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalItemId = 2,
                            ApprovalStatus = "approved",
                            CreatedAt = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            ProjectId = 1,
                            ReviewNote = "符合請款規定",
                            ReviewedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubmittedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            TotalAmount = 23500m,
                            Type = "vendor"
                        },
                        new
                        {
                            Id = 2,
                            ApprovalItemId = 2,
                            ApprovalStatus = "pending",
                            CreatedAt = new DateTime(2024, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            ProjectId = 2,
                            SubmittedById = new Guid("33333333-3333-3333-3333-333333333333"),
                            TotalAmount = 5180m,
                            Type = "travel"
                        },
                        new
                        {
                            Id = 3,
                            ApprovalItemId = 2,
                            ApprovalStatus = "rejected",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            ProjectId = 3,
                            ReviewNote = "金額超出預算上限，請重新提交",
                            ReviewedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = new Guid("11111111-1111-1111-1111-111111111111"),
                            SubmittedById = new Guid("22222222-2222-2222-2222-222222222222"),
                            TotalAmount = 20000m,
                            Type = "advance"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "admin:access",
                            Module = "Admin",
                            Name = "Admin Access"
                        },
                        new
                        {
                            Id = "2",
                            Code = "users:read",
                            Module = "Users",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = "3",
                            Code = "users:write",
                            Module = "Users",
                            Name = "Create/Edit Users"
                        },
                        new
                        {
                            Id = "4",
                            Code = "users:delete",
                            Module = "Users",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = "5",
                            Code = "roles:read",
                            Module = "Roles",
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = "6",
                            Code = "roles:write",
                            Module = "Roles",
                            Name = "Create/Edit Roles"
                        },
                        new
                        {
                            Id = "7",
                            Code = "roles:delete",
                            Module = "Roles",
                            Name = "Delete Roles"
                        },
                        new
                        {
                            Id = "8",
                            Code = "permissions:read",
                            Module = "Permissions",
                            Name = "View Permissions"
                        },
                        new
                        {
                            Id = "9",
                            Code = "permissions:write",
                            Module = "Permissions",
                            Name = "Create/Edit Permissions"
                        },
                        new
                        {
                            Id = "10",
                            Code = "permissions:delete",
                            Module = "Permissions",
                            Name = "Delete Permissions"
                        },
                        new
                        {
                            Id = "11",
                            Code = "departments:read",
                            Module = "Departments",
                            Name = "View Departments"
                        },
                        new
                        {
                            Id = "12",
                            Code = "departments:write",
                            Module = "Departments",
                            Name = "Create/Edit Departments"
                        },
                        new
                        {
                            Id = "13",
                            Code = "departments:delete",
                            Module = "Departments",
                            Name = "Delete Departments"
                        },
                        new
                        {
                            Id = "14",
                            Code = "job-titles:read",
                            Module = "JobTitles",
                            Name = "View Job Titles"
                        },
                        new
                        {
                            Id = "15",
                            Code = "job-titles:write",
                            Module = "JobTitles",
                            Name = "Create/Edit Job Titles"
                        },
                        new
                        {
                            Id = "16",
                            Code = "job-titles:delete",
                            Module = "JobTitles",
                            Name = "Delete Job Titles"
                        },
                        new
                        {
                            Id = "17",
                            Code = "approvals:read",
                            Module = "Approvals",
                            Name = "View Approvals"
                        },
                        new
                        {
                            Id = "18",
                            Code = "approvals:write",
                            Module = "Approvals",
                            Name = "Create/Edit Approvals"
                        },
                        new
                        {
                            Id = "19",
                            Code = "approvals:delete",
                            Module = "Approvals",
                            Name = "Delete Approvals"
                        },
                        new
                        {
                            Id = "20",
                            Code = "projects:read",
                            Module = "Projects",
                            Name = "View Projects"
                        },
                        new
                        {
                            Id = "21",
                            Code = "projects:write",
                            Module = "Projects",
                            Name = "Create/Edit Projects"
                        },
                        new
                        {
                            Id = "22",
                            Code = "projects:delete",
                            Module = "Projects",
                            Name = "Delete Projects"
                        },
                        new
                        {
                            Id = "23",
                            Code = "payment-requests:read",
                            Module = "PaymentRequests",
                            Name = "View Payment Requests"
                        },
                        new
                        {
                            Id = "24",
                            Code = "payment-requests:write",
                            Module = "PaymentRequests",
                            Name = "Create/Edit Payment Requests"
                        },
                        new
                        {
                            Id = "25",
                            Code = "payment-requests:delete",
                            Module = "PaymentRequests",
                            Name = "Delete Payment Requests"
                        },
                        new
                        {
                            Id = "26",
                            Code = "approval-tasks:read",
                            Module = "ApprovalTasks",
                            Name = "View Approval Tasks"
                        },
                        new
                        {
                            Id = "27",
                            Code = "approval-tasks:write",
                            Module = "ApprovalTasks",
                            Name = "Review Approval Tasks"
                        },
                        new
                        {
                            Id = "28",
                            Code = "leave-requests:read",
                            Module = "LeaveRequests",
                            Name = "View Leave Requests"
                        },
                        new
                        {
                            Id = "29",
                            Code = "leave-requests:write",
                            Module = "LeaveRequests",
                            Name = "Create/Edit Leave Requests"
                        },
                        new
                        {
                            Id = "30",
                            Code = "leave-requests:delete",
                            Module = "LeaveRequests",
                            Name = "Delete Leave Requests"
                        },
                        new
                        {
                            Id = "31",
                            Code = "travel-requests:read",
                            Module = "TravelRequests",
                            Name = "View Travel Requests"
                        },
                        new
                        {
                            Id = "32",
                            Code = "travel-requests:write",
                            Module = "TravelRequests",
                            Name = "Create/Edit Travel Requests"
                        },
                        new
                        {
                            Id = "33",
                            Code = "travel-requests:delete",
                            Module = "TravelRequests",
                            Name = "Delete Travel Requests"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BusinessAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("GoogleDriveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualAmount = 480000m,
                            BudgetAmount = 500000m,
                            BusinessAmount = 450000m,
                            Code = "P2024-001",
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            GoogleDriveUrl = "https://drive.google.com/drive/folders/example1"
                        },
                        new
                        {
                            Id = 2,
                            ActualAmount = 0m,
                            BudgetAmount = 1200000m,
                            BusinessAmount = 1100000m,
                            Code = "P2024-002",
                            CreatedAt = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            GoogleDriveUrl = "https://drive.google.com/drive/folders/example2"
                        },
                        new
                        {
                            Id = 3,
                            ActualAmount = 280000m,
                            BudgetAmount = 300000m,
                            BusinessAmount = 250000m,
                            Code = "P2025-001",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            GoogleDriveUrl = "https://drive.google.com/drive/folders/example3"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "manager",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can manage users and view reports",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = "viewer",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read-only access",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "1"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "3"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "4"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "6"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "7"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "8"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "9"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "10"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "12"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "13"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "15"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "16"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "17"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "18"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "19"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "20"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "21"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "22"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "23"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "24"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "25"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "26"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "27"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "28"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "29"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "30"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "31"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "32"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "33"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "1"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "3"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "17"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "20"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "23"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "24"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "26"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "27"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "28"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "29"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "31"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "32"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "8"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "17"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "20"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "23"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "26"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "28"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "31"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.TravelRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalItemId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStepOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalItemId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("TravelRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = "pending",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            Destination = "台南",
                            EmployeeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedCost = 3000m,
                            ProjectId = 1,
                            Purpose = "客戶現場拜訪與需求確認",
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = "approved",
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStepOrder = 1,
                            Destination = "台中",
                            EmployeeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedCost = 1500m,
                            ProjectId = 2,
                            Purpose = "供應商工廠參訪",
                            ReviewNote = "核准",
                            ReviewedAt = new DateTime(2026, 2, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedById = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResignDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JobTitleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sa@system.local",
                            IsSuperAdmin = true,
                            Name = "System Admin",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseSalary = 80000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "alice@example.com",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSuperAdmin = false,
                            JobTitleId = 4,
                            Name = "Alice Chen",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseSalary = 60000m,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "bob@example.com",
                            HireDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSuperAdmin = false,
                            JobTitleId = 2,
                            Name = "Bob Wang",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseSalary = 50000m,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "carol@example.com",
                            HireDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSuperAdmin = false,
                            JobTitleId = 1,
                            Name = "Carol Liu",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "inactive",
                            UpdatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = "admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = "manager"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = "viewer"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalRecord", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalStep", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.ApprovalItem", "ApprovalItem")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalItem");

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.PaymentRequest", "PaymentRequest")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("PaymentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.LeaveRequest", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.ApprovalItem", "ApprovalItem")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("ApprovalItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovalItem");

                    b.Navigation("Employee");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.PaymentRequest", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.ApprovalItem", "ApprovalItem")
                        .WithMany("PaymentRequests")
                        .HasForeignKey("ApprovalItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.Project", "Project")
                        .WithMany("PaymentRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Jabez.Api.Models.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalItem");

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Project", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.TravelRequest", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.ApprovalItem", "ApprovalItem")
                        .WithMany("TravelRequests")
                        .HasForeignKey("ApprovalItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.User", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApprovalItem");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Jabez.Api.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.JobTitle", "JobTitle")
                        .WithMany("Users")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.UserRole", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalItem", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("PaymentRequests");

                    b.Navigation("Steps");

                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.JobTitle", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.PaymentRequest", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Project", b =>
                {
                    b.Navigation("PaymentRequests");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
