// <auto-generated />
using System;
using Jabez.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jabez.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221033210_AddDepartmentsJobTitlesAndApprovals")]
    partial class AddDepartmentsJobTitlesAndApprovals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ApprovalItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "leave_request",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "請假申請"
                        },
                        new
                        {
                            Id = 2,
                            Code = "purchase_request",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "採購申請"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalItemId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("ApprovalSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalItemId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            JobTitleId = 4,
                            Note = "直屬部門主管核可",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovalItemId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Note = "管理部最終確認",
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ApprovalItemId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitleId = 4,
                            Note = "部門主管初核",
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 4,
                            ApprovalItemId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            JobTitleId = 4,
                            Note = "管理部主管最終核可",
                            StepOrder = 2
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MGT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "管理部",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "IT",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "資訊部",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "SLS",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "業務部",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 1,
                            Name = "工程師"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 2,
                            Name = "資深工程師"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 3,
                            Name = "主任工程師"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 4,
                            Name = "部門主管"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "admin:access",
                            Module = "Admin",
                            Name = "Admin Access"
                        },
                        new
                        {
                            Id = "2",
                            Code = "users:read",
                            Module = "Users",
                            Name = "View Users"
                        },
                        new
                        {
                            Id = "3",
                            Code = "users:write",
                            Module = "Users",
                            Name = "Create/Edit Users"
                        },
                        new
                        {
                            Id = "4",
                            Code = "users:delete",
                            Module = "Users",
                            Name = "Delete Users"
                        },
                        new
                        {
                            Id = "5",
                            Code = "roles:read",
                            Module = "Roles",
                            Name = "View Roles"
                        },
                        new
                        {
                            Id = "6",
                            Code = "roles:write",
                            Module = "Roles",
                            Name = "Create/Edit Roles"
                        },
                        new
                        {
                            Id = "7",
                            Code = "roles:delete",
                            Module = "Roles",
                            Name = "Delete Roles"
                        },
                        new
                        {
                            Id = "8",
                            Code = "permissions:read",
                            Module = "Permissions",
                            Name = "View Permissions"
                        },
                        new
                        {
                            Id = "9",
                            Code = "permissions:write",
                            Module = "Permissions",
                            Name = "Create/Edit Permissions"
                        },
                        new
                        {
                            Id = "10",
                            Code = "permissions:delete",
                            Module = "Permissions",
                            Name = "Delete Permissions"
                        },
                        new
                        {
                            Id = "11",
                            Code = "departments:read",
                            Module = "Departments",
                            Name = "View Departments"
                        },
                        new
                        {
                            Id = "12",
                            Code = "departments:write",
                            Module = "Departments",
                            Name = "Create/Edit Departments"
                        },
                        new
                        {
                            Id = "13",
                            Code = "departments:delete",
                            Module = "Departments",
                            Name = "Delete Departments"
                        },
                        new
                        {
                            Id = "14",
                            Code = "job-titles:read",
                            Module = "JobTitles",
                            Name = "View Job Titles"
                        },
                        new
                        {
                            Id = "15",
                            Code = "job-titles:write",
                            Module = "JobTitles",
                            Name = "Create/Edit Job Titles"
                        },
                        new
                        {
                            Id = "16",
                            Code = "job-titles:delete",
                            Module = "JobTitles",
                            Name = "Delete Job Titles"
                        },
                        new
                        {
                            Id = "17",
                            Code = "approvals:read",
                            Module = "Approvals",
                            Name = "View Approvals"
                        },
                        new
                        {
                            Id = "18",
                            Code = "approvals:write",
                            Module = "Approvals",
                            Name = "Create/Edit Approvals"
                        },
                        new
                        {
                            Id = "19",
                            Code = "approvals:delete",
                            Module = "Approvals",
                            Name = "Delete Approvals"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = "manager",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can manage users and view reports",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = "viewer",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read-only access",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "1"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "3"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "4"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "6"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "7"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "8"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "9"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "10"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "12"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "13"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "15"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "16"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "17"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "18"
                        },
                        new
                        {
                            RoleId = "admin",
                            PermissionId = "19"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "1"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "3"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "manager",
                            PermissionId = "17"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "2"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "5"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "8"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "11"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "14"
                        },
                        new
                        {
                            RoleId = "viewer",
                            PermissionId = "17"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResignDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AgentUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JobTitleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseSalary = 80000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "alice@example.com",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitleId = 4,
                            Name = "Alice Chen",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseSalary = 60000m,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "bob@example.com",
                            HireDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitleId = 2,
                            Name = "Bob Wang",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "active",
                            UpdatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseSalary = 50000m,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "carol@example.com",
                            HireDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitleId = 1,
                            Name = "Carol Liu",
                            PasswordHash = "$2a$11$rBnRYkdyRVRmk5V.p8PoNuXHxUZIpXe.G/j.Q/rlOH0jMNJxqm5Fy",
                            Status = "inactive",
                            UpdatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoleId = "admin"
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoleId = "manager"
                        },
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = "viewer"
                        });
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalStep", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.ApprovalItem", "ApprovalItem")
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalItem");

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Jabez.Api.Models.Entities.JobTitle", "JobTitle")
                        .WithMany("Users")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Department");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.UserRole", b =>
                {
                    b.HasOne("Jabez.Api.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jabez.Api.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.ApprovalItem", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.JobTitle", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Jabez.Api.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
