namespace Jabez.Api.Models.Dtos;

public sealed record UserDto(
    Guid      Id,
    string    Name,
    string    Email,
    string?   Avatar,
    string?   SignatureUrl,
    string[]  RoleIds,
    string    Status,
    int?      DepartmentId,
    string?   DepartmentName,
    int?      JobTitleId,
    string?   JobTitleName,
    DateTime? HireDate,
    DateTime? ResignDate,
    decimal?  BaseSalary,
    decimal?  MealAllowance,
    decimal?  OvertimePay,
    bool      SendPaySlip,
    Guid?     AgentUserId,
    string?   AgentName,
    DateTime? Birthday,
    DateTime  CreatedAt,
    bool      IsIndigenous = false,
    string?   LineUserId   = null,
    DateTime? LineLinkedAt  = null,
    string?   IndigenousProofUrl = null,
    decimal   AvatarPositionX = 50m,
    decimal   AvatarPositionY = 50m,
    decimal   AvatarScale     = 1m,
    bool      IsLowIncome    = false,
    string?   LowIncomeProofUrl  = null,
    bool      IsDisabled     = false,
    string?   DisabledProofUrl   = null,
    decimal?  HealthInsuranceOverride = null,
    decimal?  LaborInsuranceOverride  = null);

public sealed record CreateUserRequest(
    string    Name,
    string    Email,
    string    Password,
    string?   Avatar,
    string[]  RoleIds,
    string    Status      = "active",
    int?      DepartmentId = null,
    int?      JobTitleId   = null,
    DateTime? HireDate     = null,
    DateTime? ResignDate   = null,
    decimal?  BaseSalary   = null,
    decimal?  MealAllowance = null,
    decimal?  OvertimePay   = null,
    bool      SendPaySlip   = false,
    Guid?     AgentUserId  = null,
    DateTime? Birthday     = null,
    bool      IsIndigenous = false,
    bool      IsLowIncome  = false,
    bool      IsDisabled   = false,
    decimal?  HealthInsuranceOverride = null,
    decimal?  LaborInsuranceOverride  = null);

/// <summary>輕量級使用者資料（供指定審核者下拉選單用，不需 users:read 權限）</summary>
public sealed record UserLookupDto(
    Guid    Id,
    string  Name,
    int?    JobTitleId,
    string  Status);

public sealed record UpdateUserRequest(
    string?    Name,
    string?    Email,
    string?    Password,
    string?    Avatar,
    string[]?  RoleIds,
    string?    Status,
    int?       DepartmentId,
    int?       JobTitleId,
    DateTime?  HireDate,
    DateTime?  ResignDate,
    decimal?   BaseSalary,
    decimal?   MealAllowance,
    decimal?   OvertimePay,
    bool?      SendPaySlip,
    Guid?      AgentUserId,
    DateTime?  Birthday,
    bool?      IsIndigenous,
    bool?      IsLowIncome  = null,
    bool?      IsDisabled   = null,
    decimal?   HealthInsuranceOverride = null,
    decimal?   LaborInsuranceOverride  = null);
